project:
  type: book
  output-dir: docs/correction #changer display dans css et \solnfalse dnas preamble.tex pour les corrections 
  
book:
  site-path: "/TUTO_VISU_R/"  #important pour la page 404.html
  sidebar: 
    style: docked 
    search: true
    background: primary
#    title: "L. Rouvière"
#    collapse-level: 3
  title: "Visualisation avec R"
  author: "L. Rouvière"
  date: today
  date-format: long
  reader-mode: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
#    - background: light
#    - title: "Visu"
#    - contents: 
#      - index.qmd
#      - intro.qmd
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Logiciel R"
      chapters:
        - 01-intro.qmd
        - 02-objetsR.qmd
        - 03-dplyr.qmd
        - 031-programmer.qmd
    - part: "Visualisation"
      chapters:
        - 04-ggplot.qmd
        - 05-carto.qmd
        - 06-interactif.qmd
        - 07-shiny.qmd
    - part: "Statistique avec R"
      chapters:
        - 08-estimation.qmd
        - 09-regression.qmd
    - references.qmd

bibliography: references.bib

format: 
  html:
    theme: cosmo #cosmo
    highlight-style: github
    css: style.css
#    code-block-background: false
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    backgroundcolor: LightYellow
    toc: true
    reader-mode: true
#    code-tools: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    highlight-style: github
    fig-height: 3.8
    fig-width: 5.2
    include-in-header:
      - /Users/laurent/Google Drive/FICHIERS_STYLE/tuto_quarto/preamble.tex
    lang: fr
  epub: 
    keep-md: true
    toc: true
    lang: fr
    css: style.css
#    include-in-header: 
#      - preamble.tex

lang: fr
execute:
  warning: false
  echo: true
  cache: false
  freeze: auto


knitr:
  opts_chunk: 
    collapse: true
    comment: '##'
#    prompt: true


editor: source

